#version: '3'

services:
  ui:
    entrypoint: ["npm", "start"]
    environment:
      NODE_ENV: development
    image: node:20.0
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/opt/ui
    working_dir: /opt/ui

  server:
    entrypoint: ["npm", "start"]
    environment:
      NODE_ENV: development
    image: node:20.0
    links:
      - database:database
    ports:
      - "8080:8080"
    volumes:
      - ./server:/opt/server
    working_dir: /opt/server
  
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: todoapp
      MYSQL_DATABASE: todoapp
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      